# fly.toml app configuration file generated for betty-app on 2026-06-08T23:02:14Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'betty-app'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  BETTY_DB = '/data/betty.db'
  BETTY_LEAGUE_ID = '1312071038443454464'
  BETTY_MARKET_WEEK = '1'
  BETTY_SEASON = '2026'
  PORT = '3000'

[[mounts]]
  source = 'betty_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
